### ISSUE TITLE
Incompatibility between libcxxrt's cxxabi.h and libc++/libc++abi

### ISSUE THREAD

**Issue by DimitryAndric** [libcxxrt/libcxxrt#25]
After updating libcxxcrt to 03c83f5a57be8c5b1a29a68de5638744f17d28ba in https://github.com/freebsd/freebsd-src/commit/ecf4106237505fa9459ae871793b754334989c17, I'm now encountering a few errors while building recent llvm-project's libc++:

```text
FAILED: libcxx/src/CMakeFiles/cxx_shared.dir/exception.cpp.o
/home/dim/obj/llvmorg-18-init-18361-g22683463740e-freebsd15-amd64-ninja-clang-rel-1/./bin/clang++ --target=x86_64-unknown-freebsd15.0 -DLIBCXXRT -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_LINK_PTHREAD_L
In file included from /share/dim/src/llvm/release-18/libcxx/src/exception.cpp:14:
/home/dim/obj/llvmorg-18-init-18361-g22683463740e-freebsd15-amd64-ninja-clang-rel-1/runtimes/runtimes-bins/libcxx/private-abi-headers/cxxabi.h:207:7: error: '__cxa_allocate_exception' is missing exception specification 'throw()'
  207 | void *__cxa_allocate_exception(size_t thrown_size);
      |       ^
      |                                                    throw()
/home/dim/obj/llvmorg-18-init-18361-g22683463740e-freebsd15-amd64-ninja-clang-rel-1/include/c++/v1/__exception/exception_ptr.h:32:36: note: previous declaration is here
   32 | _LIBCPP_OVERRIDABLE_FUNC_VIS void* __cxa_allocate_exception(size_t) throw();
      |                                    ^
In file included from /share/dim/src/llvm/release-18/libcxx/src/exception.cpp:14:
/home/dim/obj/llvmorg-18-init-18361-g22683463740e-freebsd15-amd64-ninja-clang-rel-1/runtimes/runtimes-bins/libcxx/private-abi-headers/cxxabi.h:209:6: error: '__cxa_free_exception' is missing exception specification 'throw()'
  209 | void __cxa_free_exception(void* thrown_exception);
      |      ^
      |                                                   throw()
/home/dim/obj/llvmorg-18-init-18361-g22683463740e-freebsd15-amd64-ninja-clang-rel-1/include/c++/v1/__exception/exception_ptr.h:33:35: note: previous declaration is here
   33 | _LIBCPP_OVERRIDABLE_FUNC_VIS void __cxa_free_exception(void*) throw();
      |                                   ^
In file included from /share/dim/src/llvm/release-18/libcxx/src/exception.cpp:14:
/home/dim/obj/llvmorg-18-init-18361-g22683463740e-freebsd15-amd64-ninja-clang-rel-1/runtimes/runtimes-bins/libcxx/private-abi-headers/cxxabi.h:211:18: error: '__cxa_init_primary_exception' is missing exception specification 'throw()'
  211 | __cxa_exception *__cxa_init_primary_exception(
      |                  ^
  212 |                 void *object, std::type_info* tinfo, void (*dest)(void *));
      |
      |                                                                            throw()
/home/dim/obj/llvmorg-18-init-18361-g22683463740e-freebsd15-amd64-ninja-clang-rel-1/include/c++/v1/__exception/exception_ptr.h:36:47: note: previous declaration is here
   36 | _LIBCPP_OVERRIDABLE_FUNC_VIS __cxa_exception* __cxa_init_primary_exception(
      |                                               ^
3 errors generated.
```

libc++abi declares these functions as:

```c++
// 2.4.2 Allocating the Exception Object
extern _LIBCXXABI_FUNC_VIS void *
__cxa_allocate_exception(size_t thrown_size) throw();
extern _LIBCXXABI_FUNC_VIS void
__cxa_free_exception(void *thrown_exception) throw();
// This function is an LLVM extension, which mirrors the same extension in libsupc++ and libcxxrt
extern _LIBCXXABI_FUNC_VIS __cxa_exception*
__cxa_init_primary_exception(void* object, std::type_info* tinfo, void(_LIBCXXABI_DTOR_FUNC* dest)(void*)) throw();
```

while libcxxrt's `cxxabi.h` does not have the `throw()` specifier.

There are also copies of the declarations in libc++'s `__exception/exception_ptr.h` header (https://github.com/llvm/llvm-project/blob/main/libcxx/include/__exception/exception_ptr.h#L32):

```c++
extern "C" {
_LIBCPP_OVERRIDABLE_FUNC_VIS void* __cxa_allocate_exception(size_t) throw();
_LIBCPP_OVERRIDABLE_FUNC_VIS void __cxa_free_exception(void*) throw();

struct __cxa_exception;
_LIBCPP_OVERRIDABLE_FUNC_VIS __cxa_exception* __cxa_init_primary_exception(
    void*,
    std::type_info*,
    void(
#  if defined(_WIN32)
        __thiscall
#  endif
            *)(void*)) throw();
}
```

I am unsure what the "official" signature of these functions is, but I think it would be very bad if they *did* throw. :)

Can we adjust the libcxxrt prototypes, or do I have to go and attempt to convince the libc++(abi) people they are wrong?

**Comment by DimitryAndric** [comment]
cc @davidchisnall @itrofimow @emaste

**Comment by dankm** [comment]
I just looked, and GCC's implementation also declares this function as non-throwing, so my suggestion is to update the headers here, but maybe use noexcept instead of throw(). The latter is slated to be removed.

**Comment by DimitryAndric** [comment]
Yes, I would guess a specifier is really needed. GCC uses a `_GLIBCXX_NOTHROW` for this, for which an equivalent probably exists. In libcxxrt I see a `#define NOEXCEPT` but it's only used in `memory.cc`, not in any header (it shouldn't because that name is sure to clash with something). But overall libcxxrt seems to use plain `throw()` everywhere...

**Comment by dankm** [comment]
Yep, I saw that after I posted my comment. May as well use throw() for now and update to something like the macro in memory.cc later.

**Comment by itrofimow** [comment]
This is really embarrassing: i've messed up my local environment and ended up doing the final round of testing building against previous version of libcxxrt (without these functions in the headers) but linking against the library built from the head.

----

ABI mandates `__cxa_allocate_exception` to allocate or die:
```
 If __cxa_allocate_exception cannot allocate an exception object under these constraints, it calls terminate().

	void *__cxa_allocate_exception(size_t thrown_size);
```
and neither `__cxa_free_exception` nor `__cxa_init_primary_exception` don't throw either.

All three are `noexcept` in both [libsupc++](https://github.com/gcc-mirror/gcc/blob/9693459e030977d6e906ea7eb587ed09ee4fddbd/libstdc%2B%2B-v3/libsupc%2B%2B/cxxabi_init_exception.h#L63) and [libcxxabi](https://github.com/llvm/llvm-project/blob/fd0637cfe835d6d4d0d3ebde3663f94a7bb3cd76/libcxxabi/include/cxxabi.h#L46), so i've made a PR to mark them `noexcept` in libcxxrt as well: https://github.com/libcxxrt/libcxxrt/pull/27, which is also the easiest way to fix the issue with libc++.

----

Please don't hesitate to ping me if https://github.com/libcxxrt/libcxxrt/pull/27 doesn't make it and libc++-side fix would be needed instead, and sorry for the hassle.
